services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver-fcg
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: 'Sql@1234'
      MSSQL_PID: 'Developer'
    ports:
      - '1433:1433'
    volumes:
      - sqlserverdata:/var/opt/mssql   # persiste seus dados entre reinícios
    healthcheck:
      test: >
        /opt/mssql-tools/bin/sqlcmd 
        -S localhost 
        -U sa 
        -P "$$SA_PASSWORD" 
        -Q "SELECT 1"  
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  sqlserverdata: