trigger:
  branches:
    exclude:
      - main

pr:
  branches:
    include:
      - '*'

stages:
  - stage: CI
    displayName: 'Integração Contínua'
    jobs:
      - job: BuildAndTest
        displayName: 'Build e Testes'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - checkout: self
          - task: UseDotNet@2
            inputs:
              packageType: 'sdk'
              version: '8.0.x'
          - script: dotnet restore
            displayName: 'Restaurar dependências'
          - script: dotnet build --no-restore --configuration Release
            displayName: 'Build'
          - script: dotnet test --no-build --verbosity normal
            displayName: 'Testes'

  - stage: CD
    displayName: 'Entrega Contínua'
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    jobs:
      - job: Publish
        displayName: 'Publicar Artefatos'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - checkout: self
          - task: UseDotNet@2
            inputs:
              packageType: 'sdk'
              version: '8.0.x'
          - script: dotnet restore
            displayName: 'Restaurar dependências'
          - script: dotnet build --no-restore --configuration Release
            displayName: 'Build'
          - script: dotnet test --no-build --verbosity normal
            displayName: 'Testes'
          - script: dotnet publish --configuration Release --output $(Build.ArtifactStagingDirectory)/publish
            displayName: 'Publicar'
          - publish: $(Build.ArtifactStagingDirectory)/publish
            artifact: drop